### ISSUE TITLE
红涨绿跌按钮文字不会变

### ISSUE THREAD

**Issue by xiandan-erizo** [jsonwu5/huobi-market#11]
![image](https://user-images.githubusercontent.com/23250774/118421574-f80f6a00-b6f3-11eb-9a60-222c27b10685.png)
![image](https://user-images.githubusercontent.com/23250774/118421587-fba2f100-b6f3-11eb-9b45-a66cd371470b.png)

无论哪个都是红涨

**Comment by jsonwu5** [comment]
你使用的是哪个版本？

**Comment by xiandan-erizo** [comment]
> 你使用的是哪个版本？

1.3.0 在edge商店下载的

**Comment by xiandan-erizo** [comment]
> 你使用的是哪个版本？

好了 用了chrome商店的就没问题了
