### ISSUE TITLE
刷不出来币的价格，一直是加载中那个图片

### ISSUE THREAD

**Issue by shaohjz** [jsonwu5/huobi-market#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jsonwu5** [comment]
https://www.huobi.com/

能访问吗，直接请求的官方接口，可能需要挂梯子

**Comment by shaohjz** [comment]
打不开，那就是网络的问题QAQ

**Comment by jsonwu5** [comment]
那就需要挂梯子访问
