### ISSUE TITLE
麻烦老哥整一个打包好的插件的包，直接拖到浏览器运行的

### ISSUE THREAD

**Issue by sansamh** [jsonwu5/huobi-market#4]
不会搞前端的有点难受，虽然可以找前端同事，但无奈不是很熟。。。

**Comment by sansamh** [comment]
:+1: 如有可能，麻烦发个包给我，不胜感激，sansamhou@gmail.com

**Comment by jsonwu5** [comment]
下载这个：https://github.com/jsonwu5/huobi-market/releases/download/v1.6.1/huobi-market-v1.6.1-prod.crx

**Comment by sansamh** [comment]
> 下载这个：https://github.com/jsonwu5/huobi-market/releases/download/v1.6.1/huobi-market-v1.6.1-prod.crx

搞掂 👍

**Comment by sansamh** [comment]
> 下载这个：https://github.com/jsonwu5/huobi-market/releases/download/v1.6.1/huobi-market-v1.6.1-prod.crx

老哥 提个建议 自定义列重新打开时都会变成默认设置的 能保存自定义的状态嘛

**Comment by jsonwu5** [comment]
> > 下载这个：https://github.com/jsonwu5/huobi-market/releases/download/v1.6.1/huobi-market-v1.6.1-prod.crx
> 
> 老哥 提个建议 自定义列重新打开时都会变成默认设置的 能保存自定义的状态嘛

最新版已经处理了这个问题
