### ISSUE TITLE
点开后，加载时间很长

### ISSUE THREAD

**Issue by cactusblossom** [jsonwu5/huobi-market#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cactusblossom** [comment]
点开后，加载时间要很久（但是加载完成后，行情是可以实时更新的，应该可以排除网络问题）

**Comment by jsonwu5** [comment]
打开插件后，在插件页面右键→检查，弹出控制台，然后在控制台按F5刷新下，看下下图两个链接用时多少，截图给我看也行

![Snipaste_2021-04-29_21-50-37.png](https://ae03.alicdn.com/kf/Uc5563cf412814d5d9d5c99cdf41b599fL.png)

**Comment by cactusblossom** [comment]
![image](https://user-images.githubusercontent.com/52624291/116637185-c5484080-a995-11eb-9826-cb4708064d34.png)

**Comment by cactusblossom** [comment]
![image](https://user-images.githubusercontent.com/52624291/116637223-e6109600-a995-11eb-8b71-a9506d080f58.png)

**Comment by cactusblossom** [comment]
F5刷新感觉很快  但是一开始打开插件 加载很慢

**Comment by jsonwu5** [comment]
你自选了多少个币种？

**Comment by cactusblossom** [comment]
![image](https://user-images.githubusercontent.com/52624291/116637999-e90c8600-a997-11eb-855d-424211aeff3d.png)
就这些

**Comment by jsonwu5** [comment]
你点开ws那个链接进去看下里面的响应数据，截图给我看下。
![Snipaste_2021-04-30_11-37-20.png](https://ae04.alicdn.com/kf/Hc4415eb4ffe74c2eb5664251e85ffc1fZ.png)
